"""news translation columns

Revision ID: a874e74b6345
Revises: cfd75ee61b09
Create Date: 2026-07-17 13:22:18.665401

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a874e74b6345"
down_revision: str | Sequence[str] | None = "cfd75ee61b09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("news_items", sa.Column("title_ru", sa.String(length=512), nullable=True))
    op.add_column("news_items", sa.Column("summary_ru", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news_items", "summary_ru")
    op.drop_column("news_items", "title_ru")
    # ### end Alembic commands ###
