"""initial schema

Revision ID: cfd75ee61b09
Revises:
Create Date: 2026-07-17 10:53:24.054674

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfd75ee61b09"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("external_id", sa.String(length=256), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_sent", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(op.f("ix_news_items_is_sent"), "news_items", ["is_sent"], unique=False)
    op.create_table(
        "ports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("country", sa.String(length=64), nullable=False),
        sa.Column(
            "leg",
            sa.Enum(
                "caspian",
                "black_sea",
                "rail_cis",
                "rail_caucasus",
                "europe",
                name="corridorleg",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("is_weather_tracked", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "subscribers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tg_chat_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tg_chat_id"),
    )
    op.create_table(
        "trusted_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tg_user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tg_user_id"),
    )
    op.create_table(
        "vessels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mmsi", sa.BigInteger(), nullable=True),
        sa.Column("imo", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("operator", sa.String(length=128), nullable=True),
        sa.Column(
            "leg",
            sa.Enum(
                "caspian",
                "black_sea",
                "rail_cis",
                "rail_caucasus",
                "europe",
                name="corridorleg",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_tracked", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mmsi"),
    )
    op.create_table(
        "manual_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("port_id", sa.Integer(), nullable=True),
        sa.Column(
            "report_type",
            sa.Enum(
                "queue",
                "rate",
                "border_delay",
                "note",
                name="reporttype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["port_id"], ["ports.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["trusted_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_manual_reports_ts"), "manual_reports", ["ts"], unique=False)
    op.create_table(
        "port_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("port_id", sa.Integer(), nullable=False),
        sa.Column("vessel_id", sa.Integer(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum("arrival", "departure", name="porteventtype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source",
            sa.Enum("aisstream", "vesselapi", name="positionsource", native_enum=False, length=32),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["port_id"], ["ports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vessel_id"], ["vessels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_port_events_ts"), "port_events", ["ts"], unique=False)
    op.create_table(
        "vessel_positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vessel_id", sa.Integer(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("sog", sa.Float(), nullable=True),
        sa.Column("cog", sa.Float(), nullable=True),
        sa.Column("nav_status", sa.String(length=64), nullable=True),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source",
            sa.Enum("aisstream", "vesselapi", name="positionsource", native_enum=False, length=32),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["vessel_id"], ["vessels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vessel_positions_ts"), "vessel_positions", ["ts"], unique=False)
    op.create_index(
        "ix_vessel_positions_vessel_ts", "vessel_positions", ["vessel_id", "ts"], unique=False
    )
    op.create_table(
        "weather_alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("port_id", sa.Integer(), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "watch", "warning", "critical", name="alertlevel", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["port_id"], ["ports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weather_alerts_is_active"), "weather_alerts", ["is_active"], unique=False
    )
    op.create_table(
        "weather_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("port_id", sa.Integer(), nullable=False),
        sa.Column("wind_speed", sa.Float(), nullable=False),
        sa.Column("wind_gust", sa.Float(), nullable=False),
        sa.Column("wind_dir", sa.Float(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "raw",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["port_id"], ["ports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_weather_snapshots_port_ts", "weather_snapshots", ["port_id", "ts"], unique=False
    )
    op.create_index(op.f("ix_weather_snapshots_ts"), "weather_snapshots", ["ts"], unique=False)
    # ### end Alembic commands ###

    _seed()


def _seed() -> None:
    """Сиды справочников: порты коридора и паромы Каспия."""
    ports = sa.table(
        "ports",
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("country", sa.String),
        sa.column("leg", sa.String),
        sa.column("lat", sa.Float),
        sa.column("lon", sa.Float),
        sa.column("is_weather_tracked", sa.Boolean),
    )
    op.bulk_insert(
        ports,
        [
            {
                "code": "AKTAU",
                "name": "Актау",
                "country": "Казахстан",
                "leg": "caspian",
                "lat": 43.63,
                "lon": 51.25,
                "is_weather_tracked": True,
            },
            {
                "code": "KURYK",
                "name": "Курык",
                "country": "Казахстан",
                "leg": "caspian",
                "lat": 43.19,
                "lon": 51.65,
                "is_weather_tracked": True,
            },
            {
                "code": "BAKU_ALAT",
                "name": "Баку (Алят)",
                "country": "Азербайджан",
                "leg": "caspian",
                "lat": 39.93,
                "lon": 49.41,
                "is_weather_tracked": True,
            },
            {
                "code": "POTI",
                "name": "Поти",
                "country": "Грузия",
                "leg": "black_sea",
                "lat": 42.15,
                "lon": 41.65,
                "is_weather_tracked": True,
            },
            {
                "code": "BATUMI",
                "name": "Батуми",
                "country": "Грузия",
                "leg": "black_sea",
                "lat": 41.65,
                "lon": 41.64,
                "is_weather_tracked": True,
            },
            {
                "code": "CONSTANTA",
                "name": "Констанца",
                "country": "Румыния",
                "leg": "europe",
                "lat": 44.17,
                "lon": 28.65,
                "is_weather_tracked": True,
            },
        ],
    )

    vessels = sa.table(
        "vessels",
        sa.column("mmsi", sa.BigInteger),
        sa.column("imo", sa.BigInteger),
        sa.column("name", sa.String),
        sa.column("operator", sa.String),
        sa.column("leg", sa.String),
        sa.column("is_tracked", sa.Boolean),
    )
    # Паромы ASCO линии Курык/Актау ↔ Алят. MMSI намеренно NULL:
    # заполняются после проверки реальной видимости судов в AIS (покрытие
    # Каспия слабое — см. README), чтобы не отслеживать «мёртвые» идентификаторы.
    ferry_names = [
        "Professor Gul",
        "Academician Zarifa Aliyeva",
        "Azerbaijan",
        "Barda",
        "Balaken",
        "Shahdag",
        "Fikret Amirov",
    ]
    op.bulk_insert(
        vessels,
        [
            {
                "mmsi": None,
                "imo": None,
                "name": name,
                "operator": "ASCO",
                "leg": "caspian",
                "is_tracked": True,
            }
            for name in ferry_names
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weather_snapshots_ts"), table_name="weather_snapshots")
    op.drop_index("ix_weather_snapshots_port_ts", table_name="weather_snapshots")
    op.drop_table("weather_snapshots")
    op.drop_index(op.f("ix_weather_alerts_is_active"), table_name="weather_alerts")
    op.drop_table("weather_alerts")
    op.drop_index("ix_vessel_positions_vessel_ts", table_name="vessel_positions")
    op.drop_index(op.f("ix_vessel_positions_ts"), table_name="vessel_positions")
    op.drop_table("vessel_positions")
    op.drop_index(op.f("ix_port_events_ts"), table_name="port_events")
    op.drop_table("port_events")
    op.drop_index(op.f("ix_manual_reports_ts"), table_name="manual_reports")
    op.drop_table("manual_reports")
    op.drop_table("vessels")
    op.drop_table("trusted_sources")
    op.drop_table("subscribers")
    op.drop_table("ports")
    op.drop_index(op.f("ix_news_items_is_sent"), table_name="news_items")
    op.drop_table("news_items")
    # ### end Alembic commands ###
